import Features from "@/components/Home/Features";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Home/Hero";
import Services from "../components/Home/Services";
import EnquireServices from "../components/Home/EnquireServices";
import Footer from "../components/Home/Footer";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Navbar />
				<Hero />
				<Services />
				<EnquireServices />
				<Footer />
			</main>
		</>
	);
}
